# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Viva.find_or_create_by(id: 1, institution: "apl")
Viva.find_or_create_by(id: 2, institution: "bc")
Viva.find_or_create_by(id: 3, institution: "wm")
Viva.find_or_create_by(id: 4, institution: "cw")
Viva.find_or_create_by(id: 5, institution: "fcpl")
Viva.find_or_create_by(id: 6, institution: "gmu")
Viva.find_or_create_by(id: 7, institution: "gh")
Viva.find_or_create_by(id: 8, institution: "hrl")
Viva.find_or_create_by(id: 9, institution: "hu")
Viva.find_or_create_by(id: 10, institution: "jmu")
Viva.find_or_create_by(id: 11, institution: "lva")
Viva.find_or_create_by(id: 12, institution: "lu")
Viva.find_or_create_by(id: 13, institution: "mcc")
Viva.find_or_create_by(id: 14, institution: "odu")
Viva.find_or_create_by(id: 15, institution: "rpl")
Viva.find_or_create_by(id: 16, institution: "ru")
Viva.find_or_create_by(id: 17, institution: "rmc")
Viva.find_or_create_by(id: 18, institution: "scl")
Viva.find_or_create_by(id: 19, institution: "tbl")
Viva.find_or_create_by(id: 20, institution: "umw")
Viva.find_or_create_by(id: 21, institution: "ur")
Viva.find_or_create_by(id: 22, institution: "uva-hs")
Viva.find_or_create_by(id: 23, institution: "uva-law")
Viva.find_or_create_by(id: 24, institution: "uva-music")
Viva.find_or_create_by(id: 25, institution: "uva-sc")
Viva.find_or_create_by(id: 26, institution: "vcu-cab")
Viva.find_or_create_by(id: 27, institution: "vcu-tm")
Viva.find_or_create_by(id: 28, institution: "vhs")
Viva.find_or_create_by(id: 29, institution: "vmi")
Viva.find_or_create_by(id: 30, institution: "vmfa")
Viva.find_or_create_by(id: 31, institution: "vt")
Viva.find_or_create_by(id: 32, institution: "vsll-scv")
Viva.find_or_create_by(id: 33, institution: "vsu")
Viva.find_or_create_by(id: 34, institution: "vuu")
Viva.find_or_create_by(id: 35, institution: "wl-law")
Viva.find_or_create_by(id: 36, institution: "wl-ley")
Viva.find_or_create_by(id: 37, institution: "wcc")


